version: '3'
services:
  dev:
    build: .
    env_file:
      - ./app/.env
    volumes:
      - ./:/app
    ports:
      - 50000:8888

  app:
    build: ./app
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    ports:
      - 50001:8080

  db:
    image: postgres:14.4
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data/pgdata
      - ./db/init.d:/docker-entrypoint-initdb.d:r
