version: '3'
services:
  dev:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - 60000:8888 # jupyterlab
      - 60001:8000 # fastapi by uvicorn
  db:
    image: postgres:14.4
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - db/.env
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data/pgdata
      - ./db/init.d:/docker-entrypoint-initdb.d
    ports:
      - 54321:5432
